### PR TITLE
Linting and Logging example done on tool/generate-nightwatch-config.js

### PR DESCRIPTION
**Pull request by martinhbramwell**
Please see [Linting and Logging feature request #61](https://github.com/awatson1978/starrynight/issues/61)

### CODE REVIEW

**Comment by awatson1978** [comment]
Preliminary review, and this looks great.  Thank you for grabbing the `upstream/master` branch.  I'll probably get to pulling a local copy of `warehouseman:master` tomorrow, and will make sure a `develop` branch is available for us to use as needed.

**Comment by awatson1978** [comment]
Actually, I'm going to just roll with it, since it was a small commit.

**Comment by martinhbramwell** [comment]
Yikes!

**Comment by awatson1978** [comment]
You'd prefer a more structured process?  I'm fine with that.  

Didn't say I was going to publish it to NPM, yet.  ;)

**Pull request merged**
