### PR TITLE
ask npm for install prefix

### LINKED ISSUE #1: Error: spawn ENOENT
Following through the steps on the [StarryNight tool's web page](http://starrynight.meteor.com/) I have hit a snag. 

```
yourself@qtst:~/projects/helloworld$ starrynight -survey acceptance
Launching StarryNight.  Analyzing meteor environment...
Detected a meteor instance...
Launching nightwatch bridge...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

yourself@qtst:~/projects/helloworld$ meteor update
This project is already at Meteor 1.1.0.2, the latest release.
Your packages are at their latest compatible versions.

yourself@qtst:~/projects/helloworld$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

yourself@qtst:~/projects/helloworld$ npm --version
1.3.10
```

Any ideas?

### PR DESCRIPTION
**Pull request by meonkeys**
This should fix #1.

Lots of whitespace changed because I indented a long `switch` block. This diff is short if you ignore whitespace changes.

### CODE REVIEW

**Comment by awatson1978** [comment]
Ooooo....  This look great.  Thanks so much!  Have you run through the test script and is everything working?  I'm tempted to merge this in, and let it sit for a few days before publishing to npm.

**Comment by meonkeys** [comment]
Cool!

Test script? No, I just ran `bin/starrynight.js` stand-alone and made sure it could find npm's `prefix`.

Is there an easy way to test everything?

**Comment by awatson1978** [comment]
:)
That should probably be sufficient.

Right now, the walkthrough in the Examples section on http://starrynight.meteor.com is working as a test script.  Need to automate it; but for the time being its better than nothing.  Will want to run through that script before publishing to npm.

**Comment by meonkeys** [comment]
Ah, gotcha. I used `sudo npm link` to globally install from my clone's working dir, then I was able to test this version of `starrynight`.

Already found one issue walking through the script. I'll file it.

**Pull request merged**
